CMSProject/Models/GoodsReceipt.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsReceipt()
        {
            this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetail>();
        }
    
        public int GoodsReceiptID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string GoodsReceiptName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Creator { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }
    }
}

CMSProject/Controllers/GoodsReceiptsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CMSProject.Models;
using PagedList;

namespace CMSProject.Controllers
{
    public class GoodsReceiptsController : Controller
    {
        private CMSEntities db = new CMSEntities();
        List<Storage> LstStorage = new List<Storage>(); //Khởi tạo Class Storage lên

        
        public ActionResult Index()
        {
            var goodsReceipts = db.GoodsReceipts;
            return View(goodsReceipts.ToList());
        }

        // GET: GoodsReceipts/Details/5
        public ActionResult Details(int? id)
        {           

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodsReceipt goodsReceipt = db.GoodsReceipts.Find(id);
            //Viết ViewBag tại đây
            if (goodsReceipt == null)
            {
                return HttpNotFound();
            }
           
            ViewBag.lstGoodsReceiptDetail = db.GoodsReceiptDetails.Where(x => x.GoodsReceiptID == id).ToList();
            return View(goodsReceipt);
        }
        public PartialViewResult _Index(int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10;
            var model = db.GoodsReceipts.OrderBy(n => n.GoodsReceiptID).ToPagedList(pageNumber, pageSize);
            return PartialView(model);
        }


        // GET: GoodsReceipts/Create
        public ActionResult Create()
        {
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "SupplierName");
            return View();
        }

        // POST: GoodsReceipts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GoodsReceiptID,SupplierID,GoodsReceiptName,AddedDate,Creator,Status,Total")] GoodsReceipt goodsReceipt)
        {
            CMSEntities db = new CMSEntities();
            if (ModelState.IsValid)
            {
                goodsReceipt.Creator = Session["AdminName"].ToString();
                goodsReceipt.Status = 3;
                goodsReceipt.AddedDate = DateTime.Now;
                db.GoodsReceipts.Add(goodsReceipt);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "SupplierName", goodsReceipt.SupplierID);
            return View(goodsReceipt);
        }

        // GET: GoodsReceipts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodsReceipt goodsReceipt = db.GoodsReceipts.Find(id);
            if (goodsReceipt == null)
            {
                return HttpNotFound();
            }
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "SupplierName", goodsReceipt.SupplierID);
            return View(goodsReceipt);
        }

        // POST: GoodsReceipts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GoodsReceiptID,SupplierID,GoodsReceiptName,AddedDate,Creator,Status,Total")] GoodsReceipt goodsReceipt)
        {
            //int idSupplier = Int32.Parse(TempData["idSupplier"].ToString());
            if (ModelState.IsValid)
            {
                goodsReceipt.AddedDate = DateTime.Now;
                db.Entry(goodsReceipt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "SupplierName", goodsReceipt.SupplierID);
            return View(goodsReceipt);
        }

        // GET: GoodsReceipts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodsReceipt goodsReceipt = db.GoodsReceipts.Find(id);
            if (goodsReceipt == null)
            {
                return HttpNotFound();
            }
            return View(goodsReceipt);
        }

        // POST: GoodsReceipts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GoodsReceipt goodsReceipt = db.GoodsReceipts.Find(id);
            db.GoodsReceipts.Remove(goodsReceipt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Debug Button "Them vao"
        public ActionResult AddGoodsReceipt(int id)
        {
            if (Session["Storage"] != null)
            {
                LstStorage = Session["Storage"] as List<Storage>;
            }
            var lstGoodsReceipt = LstStorage.Where(n => n.GoodsReceiptID == id).ToList();
            if (lstGoodsReceipt.Count > 0)
            {
                TempData["TotalGoodsReceipt"] = lstGoodsReceipt.Sum(n => n.Total);
            }
            else
            {
                TempData["TotalGoodsReceipt"] = 0;
            }
            GoodsReceipt goodsReceipt = db.GoodsReceipts.Find(id);
            ViewBag.totalGoodsReceiptDetail = TempData["TotalGoodsReceipt"];
            TempData["idGoodsReceipt"] = id;
            return View(goodsReceipt);
        }

        //Show ra danh sách product
        public ActionResult LstPro()
        {
            ViewBag.idGoodsReceipt = TempData["idGoodsReceipt"];
            var dataPro = db.Products.ToList();
            return View(dataPro);
        }

        [HttpPost]
        public ActionResult LstPro(string maSP)
        {
            var result = from p in db.Products
                         select p;
            if (!String.IsNullOrEmpty(maSP))
            {
                result = result.Where(n => n.ProductCode.Contains(maSP));
            }
            ViewBag.idGoodsReceipt = TempData["idGoodsReceipt"];
            return View(result);
        }
        
        public ActionResult LstGoodsReceipt()
        {
            if (Session["Storage"] == null)
            {
                LstStorage = new List<Storage>();
            }
            else
            {
                LstStorage = Session["Storage"] as List<Storage>;
            }
            int idStorage = Int32.Parse(TempData["idGoodsReceipt"].ToString());
            var dataStorage = LstStorage.Where(n => n.GoodsReceiptID == idStorage).ToList();
            return View(dataStorage);
        }

        //Xử lý chức năng thêm sản phẩm vào LstGoodsReceipt
        [HttpPost]
        public ActionResult LstGoodsReceipt(int? id, int? idGoodsReceipt)
        {
            //Khởi tạo flag nếu bằng false thì cho phép thêm mới còn ngược lại thì sẽ cập nhật số lượng
            bool flag = false;
            if (Session["Storage"] == null)
            {
                LstStorage = new List<Storage>();
            }
            else
            {
                LstStorage = Session["Storage"] as List<Storage>;
                //Khởi tạo biến danh sách ở tại cái phiếu nhập ấy để chỉ tăng số lượng ở trong danh sách phiếu nhập này
                var lstGoodsReceipt = LstStorage.Where(n => n.GoodsReceiptID == idGoodsReceipt).ToList();
                foreach (var item in lstGoodsReceipt)
                {
                    //Kiểm tra nếu như đã tồn tại cái id sản phẩm rồi thì nó sẽ update số lượng tăng thêm 1 sau mỗi lần click
                    if (item.ProductID == id)
                    {
                        flag = true;
                        item.Quantity += 1;
                        item.Total = item.Quantity * item.UnitPrice;
                        break;
                    }
                }
            }
            Product product = db.Products.Where(n => n.ProductID == id).FirstOrDefault();
            int idGoods_receipt = idGoodsReceipt.Value;
            if (flag == false)
            {
                Storage storage = new Storage();
                storage.ProductID = id.Value;
                storage.GoodsReceiptID = idGoods_receipt;
                storage.ProductName = product.ProductName;
                storage.Quantity = 1;
                storage.Total = storage.Quantity * storage.UnitPrice;
                LstStorage.Add(storage);
            }
            Session["Storage"] = LstStorage;
            return RedirectToAction("AddGoodsReceipt/" + idGoods_receipt);
        }

        //Cập nhật số lượng và đơn giá
        [HttpPost]
        public ActionResult updateQuantityAndUnitPrice(int id, int? idGoodsReceipt, int quantitied, int Priced, int unitPriced)
        {
            if (Session["Storage"] == null)
            {
                LstStorage = new List<Storage>();
            }
            else
            {
                LstStorage = Session["Storage"] as List<Storage>;
            }
            var lstGoodsReceipt = LstStorage.Where(n => n.GoodsReceiptID == idGoodsReceipt).ToList();
            if (lstGoodsReceipt != null)
            {
                lstGoodsReceipt.Where(n => n.ProductID == id).FirstOrDefault().Quantity = quantitied;

CMSProject/Views/GoodsReceipts/AddGoodsReceipt.cshtml
@model CMSProject.Models.GoodsReceipt
@{
    ViewBag.Title = "AddGoodsReceipt";
    Layout = "~/Views/Shared/admin.cshtml";
}


<div class="row search-par">
    <div class="col-md-6 search-child" style="margin-top:20px;">
        <div class="search-zone" style="float:right;border:1px solid #000000;margin-bottom: 13px;">
            <input type="text" name="maSP" placeholder="Mã sản phẩm ..." /> <button class="btn btn-primary"><i class="fa fa-search" aria-hidden="true" style="font-weight:bold;"></i></button>
        </div>
    </div>
    <div class="col-md-6"></div>
</div>
<div class="row pro-view">
    <div class="col-md-6 pro-child" style="border:1px solid #808080;height:500px; margin-top:20px;overflow:auto;">
        @Html.Action("LstPro", "GoodsReceipts")
    </div>
    <div class="col-md-6" style="border:1px solid #808080;height:500px; margin-top:20px;overflow:auto;">
        @Html.Action("LstGoodsReceipt", "GoodsReceipts")
    </div>
</div>
<div class="modal-footer">
    <table>
        <tr>
            <th>Tổng tiền: </th>
            <th style="color:red;">@ViewBag.totalGoodsReceiptDetail.ToString("#,###") VND</th>
            <td>
                <button onclick="LuuVao(@Model.GoodsReceiptID)" class="btn btn-primary">Lưu phiếu</button>
            </td>
        </tr>
    </table>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        $('.search-zone > input').on('keydown', function (e) {
            let val;
            let getData = $(this).closest('.search-zone').parent('.search-child').parent('.search-par').siblings('.pro-view').children('.pro-child')/*siblings('.page-product').children('.my-product');*/
            if (event.keyCode == 8) {
                val = $(this).val();
                val = val.substr(0, val.length - 1);
            }
            else if (event.keyCode >= 8 && event.keyCode <= 90) {
                val = $(this).val() + String.fromCharCode(event.keyCode);
            }
            else {
                return;
            }
            val = val.toLowerCase();
            $.ajax({
                url: '/GoodsReceipts/LstPro',
                type: 'POST',
                dataType: 'html',
                data: { maSP: val },
            })
                .done(function (data) {
                    getData.html(data);
                    //console.log("success");
                })
                .fail(function () {
                    //console.log("error");
                })
                .always(function () {
                    //console.log("complete");
                });
        })
    })
</script>
<script>
    function LuuVao(id) {
        var f = confirm("Lưu vào kho?");
        if (f == true) {
            window.location.href = "/GoodsReceipts/SaveGoodsReceiptToDb/" + id;
        }
    }
</script>

CMSProject/Views/GoodsReceipts/Create.cshtml
@model CMSProject.Models.GoodsReceipt

@{
    //ViewBag.Title = "Create";
    Layout = "~/Views/Shared/admin.cshtml";
}

@*<h2>Create</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>GoodsReceipt</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, "Nhà phân phối", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GoodsReceiptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.GoodsReceiptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GoodsReceiptName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.AddedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.AddedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AddedDate, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.Status,new List<SelectListItem>()
           {
               new SelectListItem{Text="Đã thanh toán", Value="1"},
               new SelectListItem{Text="Chưa thanh  toán",Value="2"},
               new SelectListItem{Text="Đang nhập hàng",Value="3"}
           }, "--Chon--" , htmlAttributes : new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("<< Quay lại danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CMSProject/Views/GoodsReceipts/Delete.cshtml
@model CMSProject.Models.GoodsReceipt

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/admin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GoodsReceipt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GoodsReceiptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GoodsReceiptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.SupplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.SupplierName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("<< Quay lại danh sách", "Index")
        </div>
    }
</div>

CMSProject/Views/GoodsReceipts/Details.cshtml
@model CMSProject.Models.GoodsReceipt

@{

    Layout = "~/Views/Shared/admin.cshtml";
}

@*<h2>Details</h2>*@

<div>
    @*<h4>GoodsReceipt</h4>*@
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.GoodsReceiptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GoodsReceiptName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.SupplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.SupplierName)
        </dd>

    </dl>
</div>
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit Price</th>          
            <th>Total</th>
         
        </tr>
        @foreach (var item in ViewBag.lstGoodsReceiptDetail)
        {
        <tr>
            <td>@item.Product.ProductName</td>
            <td>@item.Quantity </td>
            <td>@item.UnitPrice</td>
            <td>@item.Total</td>
        </tr>
        }
    </table>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GoodsReceiptID }) |
    @Html.ActionLink("<< Quay lại danh sách", "Index")
</p>

CMSProject/Views/GoodsReceipts/Edit.cshtml
@model CMSProject.Models.GoodsReceipt

@{

    Layout = "~/Views/Shared/admin.cshtml";
}

@*<h2>Edit</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GoodsReceipt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GoodsReceiptID)

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, "Nhà phân phối", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GoodsReceiptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GoodsReceiptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GoodsReceiptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddedDate, new { htmlAttributes = new { @class = "form-control",@readonly=true } })
                @Html.ValidationMessageFor(model => model.AddedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status,new List<SelectListItem>()
           {
               new SelectListItem{Text="Đã thanh toán",Value = "1" },
               new SelectListItem{Text="Chưa thanh toán",Value = "2" }
           },"--Chọn--",   htmlAttributes: new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style= "display:none">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập nhật" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("<< Quay lại danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CMSProject/Views/GoodsReceipts/Index.cshtml
@model IEnumerable<CMSProject.Models.GoodsReceipt>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/admin.cshtml";
}

<div class="modal-header">
    <h2>Danh sách phiếu nhập</h2>
</div>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
@*<a href='@Url.Action("Create", "GoodsReceipts")' class="btn btn-primary" style="float:right;margin-right:22px;">Tạo mới phiếu nhập</a><br>*@

<p>
    <a href="/GoodsReceipts/Create" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i></a>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GoodsReceiptName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier.SupplierName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creator)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GoodsReceiptName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.SupplierName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creator)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>*@
            <td>
                @if (item.Status == 1)
                {
                    <text>Đã thanh toán</text>
                }
                @if (item.Status == 2)
                {
                    <text>Chưa thanh toán</text>
                }
                else
                {
                    if (item.Status == 3)
                    {
                        <text>Đang nhập hàng</text>
                    }
                }
            </td>
            <td>
                @if (item.Total > 0)
                {
                    @item.Total.Value.ToString("#,###")
                }
                else
                {
                    <text>0</text>
                }
                VND
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.GoodsReceiptID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.GoodsReceiptID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.GoodsReceiptID }) |*@


                @Html.ActionLink("  ", "Edit", new { id = item.GoodsReceiptID }, new { @class = "btn btn-warning fa fa-pencil" })
                @Html.ActionLink("  ", "Details", new { id = item.GoodsReceiptID }, new { @class = "btn btn-info fa fa-info-circle" })
                @*@Html.ActionLink("  ", "Delete", new { id = item.GoodsReceiptID }, new { @class = "btn btn-danger fa fa-times" })*@
                @if (item.Total == null)
                {
                    <a href="/GoodsReceipts/AddGoodsReceipt/@item.GoodsReceiptID" class="btn btn-danger">Thêm vào</a>
                }
            </td>
        </tr>
    }

</table>