CMSClient/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CMSProject.Models;
using PagedList;

namespace CMSProject.Client.Controllers
{
    public class ClientsController : Controller
    {
        List<Carts> lstCarts = new List<Carts>();
        private CMSEntities db = new CMSEntities();
        List<OrderClients> lstOrderClients = new List<OrderClients>();
        // GET: ListProducts

        public PartialViewResult GetPaging(int? page)
        {
            List<Product> lstproduct = new List<Product>();
            lstproduct = db.Products.ToList();
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return PartialView("_PartialViewProduct", lstproduct.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ProductPagedIndex()
        {
            return View();
        }

        public ActionResult ProductIndex()
        {
            if (Session["CustomerID"] != null)
            {
                ViewBag.IdOrd = Int32.Parse(Session["CustomerID"].ToString());
            }
            ViewBag.lstCategories = db.Categories.ToList();
            var lstPro = db.Products.Where(n => n.Status == 1).ToList();
            return View(lstPro);
        }

        //Thêm sản phẩm vào giỏ hàng
        [HttpPost]
        public ActionResult AddToCartClient(int id, int? IdOrderClient)
        {
            if (Session["CustomerID"] == null)
            {
                return RedirectToAction("Login", "Customers");
            }
            else
            {
                bool flag = false;
                int idOrder = IdOrderClient.Value;
                if (Session["Cart"] == null)
                {
                    lstCarts = new List<Carts>();
                }
                else
                {
                    lstCarts = Session["Cart"] as List<Carts>;
                    var listCart = lstCarts.Where(n => n.OrderID == idOrder).ToList();
                    foreach (var carts in listCart)
                    {
                        if (carts.ProductID == id)
                        {
                            flag = true;
                            carts.Quantity += 1;
                            carts.Total = carts.UnitPrice * carts.Quantity;
                            break;
                        }
                    }
                }
                Product product = db.Products.Where(n => n.ProductID == id).FirstOrDefault();
                if (flag == false)
                {
                    Carts c = new Carts();
                    c.ProductID = id;
                    c.OrderID = idOrder;
                    c.ProductName = product.ProductName;
                    c.Quantity = 1;
                    c.UnitPrice = Convert.ToDecimal(product.Price);
                    c.Total = c.UnitPrice * c.Quantity;
                    lstCarts.Add(c);
                }
                Session["Cart"] = lstCarts;
                return RedirectToAction("ProductIndex");
            }
        }

        //Hiển thị danh sachsanr phẩm trong giỏ hàng
        public ActionResult ClientCartIndex(int? id)
        {
            if (Session["CustomerID"] == null)
            {
                return RedirectToAction("Login", "Customers");
            }
            else
            {
                if (Session["Order"] == null)
                {
                    lstOrderClients = new List<OrderClients>();
                }
                else
                {
                    lstOrderClients = Session["Order"] as List<OrderClients>;
                }
                if (Session["Cart"] == null)
                {
                    lstCarts = new List<Carts>();
                }
                else
                {
                    lstCarts = Session["Cart"] as List<Carts>;
                }
                var dataCarts = lstCarts.Where(n => n.OrderID == id).ToList();
                if (dataCarts.Count > 0)
                {
                    TempData["TotalCart"] = dataCarts.Sum(n => n.Total);
                }
                else
                {
                    TempData["TotalCart"] = 0;
                }
                ViewBag.totalCart = TempData["TotalCart"];
                ViewBag.Error = TempData["ErrorQuantity"];
                ViewBag.messageSuccess = TempData["MessageSuccess"];
                OrderClients order = lstOrderClients.Find(n => n.OrderID == id);
                return View(order);
            }
        }

        // Danh sách sản phẩm đã được thêm vào giỏ hàng
        public ActionResult _ListCartClient()
        {
            if (Session["Cart"] == null)
            {
                lstCarts = new List<Carts>();
            }
            else
            {
                lstCarts = Session["Cart"] as List<Carts>;
            }
            int IdOrd = Int32.Parse(Session["CustomerID"].ToString());
            var dataCarts = lstCarts.Where(n => n.OrderID == IdOrd).ToList();
            return View(dataCarts);
        }

        public ActionResult BlogIndex()
        {
            var lstBlog = db.Blogs.ToList();
            return View(lstBlog);
        }

        public ActionResult BlogDetail(int? id)
        {

            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            var blog = db.Blogs.Where(x => x.BlogID == id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        public ActionResult CustomerDetail(int? id)
        {

            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            var customer = db.Customers.Where(x => x.CustomerID == id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult ProductDetail(int? id)
        {
            var product = db.Products.Where(n => n.ProductID == id).FirstOrDefault();
            if (product == null)
            {
                return RedirectToAction("ProductIndex");
            }
            return View(product);
        }

        //Xóa sản phẩm trong giỏ hàng
        [HttpPost]
        public ActionResult RemoveProductInCart(int id, int? idOrd)
        {
            if (Session["Cart"] != null)
            {
                lstCarts = Session["Cart"] as List<Carts>;
            }
            if (lstCarts != null)
            {
                Carts c = lstCarts.Where(n => n.ProductID == id).FirstOrDefault();
                lstCarts.Remove(c);
            }
            int idOrder = idOrd.Value;
            return RedirectToAction("ClientCartIndex/" + idOrder);
        }

        //Cập nhật số lượng trong giỏ hàng
        [HttpPost]
        public ActionResult UpdateQuantity(int id, int quantitied, int? idOrd)
        {
            if (Session["Cart"] != null)
            {
                lstCarts = Session["Cart"] as List<Carts>;
            }
            var listCart = lstCarts.Where(n => n.OrderID == idOrd).ToList();
            if (listCart != null)
            {
                var product = db.Products.Where(n => n.ProductID == id).ToList();
                foreach (var pro in product)
                {
                    if (quantitied <= pro.Quantity)
                    {
                        listCart.Where(n => n.ProductID == id).FirstOrDefault().Quantity = quantitied;
                        listCart.Where(n => n.ProductID == id).FirstOrDefault().Total = lstCarts.Where(n => n.ProductID == id).FirstOrDefault().UnitPrice * quantitied;
                    }
                    else
                    {
                        TempData["ErrorQuantity"] = "Rất tiếc, số lượng của một sản phẩm mà bạn cần không đủ so với trong kho của chúng tôi! Vui lòng nhập lại.";
                    }
                }
            }
            int idOrder = idOrd.Value;
            Session["Cart"] = lstCarts;
            return RedirectToAction("ClientCartIndex/" + idOrder);
        }


        //public ActionResult SaveToOrder()
        //{
        //    ViewBag.messageSuccess = TempData["ViewBag.messageSuccess"];
        //    return View("ProductIndex");
        //}
        //Lưu lại Order và OrderDetail
        //Them viewbag message success  
        public ActionResult SaveToOrder(int? id)
        {
            if (Session["Cart"] == null)
            {
                lstCarts = new List<Carts>();
            }
            else
            {
                lstCarts = Session["Cart"] as List<Carts>;
            }
            if (Session["Order"] == null)
            {
                lstOrderClients = new List<OrderClients>();
            }
            else
            {
                lstOrderClients = Session["Order"] as List<OrderClients>;
            }
            //int idClient = Convert.ToInt32(Session["UserId"]);
            var listOrderClient = lstOrderClients.Where(n => n.CustomerID == id).FirstOrDefault();
            Order order = new Order();
            order.CustomerID = id;
            order.OrderName = 2;
            order.CustomerName = listOrderClient.CustomerName;
            order.CustomerEmail = listOrderClient.CustomerEmail;
            order.Phone = listOrderClient.Phone;
            order.CreateDate = DateTime.Now;
            order.OrderCreate = listOrderClient.CustomerName;
            order.Status = 1;
            db.Orders.Add(order);
            db.SaveChanges();
            //Lấy ra idOrder cuối cùng
            var listOrders = db.Orders.Where(n => n.CustomerID == id).ToList();
            int idOrderMax = listOrders.Max(n => n.OrderID);
            //Tiến hành lưu từ Cart vào OrderDetail

CMSClient/Views/Clients/BlogDetail.cshtml
@model IEnumerable<CMSProject.Models.Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/customer.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BlogIndex</title>
</head>
<body>
    <section class="blog_area single-post-area padding_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        @foreach (var item in Model)
                        {
                            <article class="blog_item">
                                @*<div class="blog_item_img">
                                        <img class="card-img rounded-0" src="img/blog/single_blog_1.png" alt="">
                                        <a href="#" class="blog_item_date">
                                            <h3>15</h3>
                                            <p>Jan</p>
                                        </a>
                                    </div>*@
                                <div class="blog_details">
                                    <a class="d-inline-block" href="#BlogDetail">
                                        <h2>@item.BlogTitle</h2>
                                    </a>
                                    <p>
                                        @Html.Raw(item.BlogContent)                                      
                                    </p>
                                    <p>
                                        @item.DateCreated
                                    </p>
                                    @*<ul class="blog-info-link">
            <li><a href="#"><i class="far fa-user"></i> Travel, Lifestyle</a></li>
            <li><a href="#"><i class="far fa-comments"></i> 03 Comments</a></li>
        </ul>*@
                                </div>
                            </article>
                        }
                        @*<nav class="blog-pagination justify-content-center d-flex">
                                <ul class="pagination">
                                    <li class="page-item">
                                        <a href="#" class="page-link" aria-label="Previous">
                                            <i class="ti-angle-left"></i>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link">1</a>
                                    </li>
                                    <li class="page-item active">
                                        <a href="#" class="page-link">2</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link" aria-label="Next">
                                            <i class="ti-angle-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>*@
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <form action="#">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder='Search Keyword'
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btn" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1"
                                        type="submit">
                                    Search
                                </button>
                            </form>
                        </aside>
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Resaurant food</p>
                                        <p>(37)</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Travel news</p>
                                        <p>(10)</p>
                                    </a>
                                </li>
                            
                            </ul>
                        </aside>
                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">Recent Post</h3>
                            <div class="media post_item">
                                <img src="img/post/post_1.png" alt="post">
                                <div class="media-body">
                                    <a href="single-blog.html">
                                        <h3>From life was you fish...</h3>
                                    </a>
                                    <p>January 12, 2019</p>
                                </div>
                            </div>
                        
                        </aside>
                        <aside class="single_sidebar_widget tag_cloud_widget">
                            <h4 class="widget_title">Tag Clouds</h4>
                            <ul class="list">
                                <li>
                                    <a href="#">project</a>
                                </li>
                                <li>
                                    <a href="#">love</a>
                                </li>
                                <li>
                                    <a href="#">technology</a>
                                </li>
                                <li>
                                    <a href="#">travel</a>
                                </li>
                                <li>
                                    <a href="#">restaurant</a>
                                </li>
                                <li>
                                    <a href="#">life style</a>
                                </li>
                                <li>
                                    <a href="#">design</a>
                                </li>
                                <li>
                                    <a href="#">illustration</a>
                                </li>
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget instagram_feeds">
                            <h4 class="widget_title">Instagram Feeds</h4>
                            <ul class="instagram_row flex-wrap">
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_5.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_6.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_7.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_8.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_9.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_10.png" alt="">
                                    </a>
                                </li>
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget newsletter_widget">
                            <h4 class="widget_title">Newsletter</h4>
                            <form action="#">
                                <div class="form-group">
                                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                           onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1"
                                        type="submit">
                                    Subscribe
                                </button>
                            </form>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

CMSClient/Views/Clients/ClientCartIndex.cshtml
@model CMSProject.Models.OrderClients

@{
    ViewBag.Title = "ClientCartIndex";
    Layout = "~/Views/Shared/customer.cshtml";
}


<style>
    .message-success {
        color: aliceblue;
        background-color: #95e2b0;
        border-radius: 15px;
        width: 430px;
        text-align: center;
        height: 55px;
        line-height: 55px;
        font-size: 25px;
        margin: 15px auto;
    }
</style>

@if (ViewBag.messageSuccess != null)
{
    <p class="message-success">@ViewBag.messageSuccess</p>
}

@if (ViewBag.Error != null)
{
    <div class="modal-content" style="width:500px;margin:0px auto;">
        <div class="modal-header">
            <h2><strong>Error:</strong></h2>
        </div>
        <div class="modal-body">
            <p style="color:red;">@ViewBag.Error</p>
        </div>
    </div>
}

<div class="container" style="margin-top:50px;">
    @if (ViewBag.totalCart <= 0)
    {
        <text>
            <div style="text-align:center;">
                <div style="font-weight:bold;">
                    <i class="fa fa-cart-arrow-down" style="font-size:150px;" aria-hidden="true"></i>
                </div>
                <div style="margin:15px;font-size:20px;">
                    Không có sản phẩm nào trong giỏ hàng của bạn.
                </div>
                <div>
                    <a href="/Clients/ProductIndex" class="btn btn-warning">Tiep tuc mua sam</a>
                </div>
            </div>
        </text>
    }
    else
    {
        <div class="modal-body">
            @Html.Action("_ListCartClient", "Clients")
        </div>
        <div class="modal-footer">
            <table style="float:right;">
                <tr>
                    <th>Tổng thanh toán: </th>
                    <th style="color:red;">
                        @if (ViewBag.totalCart > 0)
                        {
                            @ViewBag.totalCart.ToString("#,###")
                        }
                        else
                        {
                            <text>0</text>
                        } VND
                    </th>
                    <td>
                        <button onclick="SaveToOrderDetail(@Model.OrderID)" class="btn btn-success">Đặt hàng</button>
                    </td>
                </tr>
            </table>
        </div>
    }
</div>
<script>
    function SaveToOrderDetail(id) {
        window.location.href = "/Clients/SaveToOrder/" + id;
    }
</script>

CMSClient/Views/Clients/ClientDetail.cshtml
@model CMSProject.Models.Customer

@{
    ViewBag.Title = "ClientDetail";
    Layout = "~/Views/Shared/customer.cshtml";
}

<h2>ClientDetail</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsEmailVerified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEmailVerified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivationCode)
        </dd>

    </dl>
</div>
<p class="modal-footer">
    <a href="/Clients/ClientEdit/@Model.CustomerID" class="btn btn-warning">Chỉnh sửa tài khoản</a> |
    @Html.ActionLink("Back to List", "Index")
</p>

CMSClient/Views/Clients/ClientEdit.cshtml
@model CMSProject.Models.Customer

@{
    ViewBag.Title = "ClientEdit";
    Layout = "~/Views/Shared/customer.cshtml";
}

<h2>ClientEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerID)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsEmailVerified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsEmailVerified)
                    @Html.ValidationMessageFor(model => model.IsEmailVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActivationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CMSClient/Views/Clients/ClientFeedback.cshtml
@model CMSProject.Models.Feedback

@{
    ViewBag.Title = "ClientFeedback";
    Layout = "~/Views/Shared/customer.cshtml";
}


<style>
    .message-success {
        color: aliceblue;
        background-color: green;
    }
</style>
<style>
    textarea.form-control {
        height: 100px;
        margin-bottom: 120px;
    }
</style>
@if (ViewBag.messageSuccess != null)
{
    <p class="message-success">@ViewBag.messageSuccess</p>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style=" margin-top: 160px;">
        <h4>Phản hồi của khách hàng</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group" style="height:600px;">
            @*@Html.LabelFor(model => model.FeedbackContent, htmlAttributes: new { @class = "control-label col-md-2" })*@
            Nội dung feedback<br>
            <div class="col-md-10">
                @Html.EditorFor(model => model.FeedbackContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FeedbackContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gửi đi" class="btn btn-success" style="margin-top: -920px;" />
            </div>
        </div>
    </div>
}

CMSClient/Views/Clients/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/customer.cshtml";
}

<style>
    .footer_part {
        margin-top: 200px;
    }
</style>
<h2>Contact</h2>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3659.081251881219!2d106.80822481488138!3d20.911440086062047!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x314a640717d0701d%3A0xaebf770557273e98!2zQ-G6qW0gTGEsIFnDqm4gSMawbmcsIFF14bqjbmcgTmluaCwgVmlldG5hbQ!5e1!3m2!1sen!2s!4v1574502298510!5m2!1sen!2s" width="1000" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

CMSClient/Views/Clients/ProductPagedIndex.cshtml
@model PagedList.IPagedList<CMSProject.Models.Product>
@using PagedList.Mvc

@*@{

    Layout = "~/Views/Shared/customer.cshtml";
}*@

<div id="top_pageniation">
    @{Html.RenderAction("GetPaging", "Clients", new { Page = 1 }); }
</div>